version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    volumes: [ "pg_data:/var/lib/postgres/data" ]
    ports: [ "5432:5432/tcp" ]
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: hacksawtv

volumes:
  pg_data: {}