# fly.toml app configuration file generated for hacksaw-tv on 2023-04-29T17:16:10+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hacksaw-tv"
primary_region = "lhr"
kill_signal = "SIGTERM"

[deploy]
  release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "hacksaw-tv.fly.dev"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  [http_service.concurrency]
    type = "connections"
    # Phoenix can handle a *lot* of concurrent TCP connections
    # "Requests"-based scaling may be more appropriate
    hard_limit = 1000
    soft_limit = 1000
