# fly.toml app configuration file generated for hacksaw-tv-streamer on 2023-04-29T11:45:27+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hacksaw-tv-streamer"
primary_region = "lhr"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[env]
  PRIMARY_REGION = "lhr"

[[services]]
  protocol = "tcp"
  internal_port = 1935
  processes = ["app"]

  [[services.ports]]
    port = 1935

[[services]]
  protocol = "tcp"
  internal_port = 3333
  processes = ["app"]

  [[services.ports]]
    port = 3334
    handlers = ["tls"]

[[services]]
  protocol = "tcp"
  internal_port = 3478
  processes = ["app"]

  [[services.ports]]
    port = 3478

[[services]]
  protocol = "tcp"
  internal_port = 9000
  processes = ["app"]

  [[services.ports]]
    port = 9000

[[services]]
  protocol = "udp"
  internal_port = 9999
  processes = ["app"]

  [[services.ports]]
    port = 9999

[[services]]
  protocol = "udp"
  internal_port = 4000
  processes = ["app"]

  [[services.ports]]
    port = 4000
